
@startuml
!option handwritten true
!include_many ../data-management-style.txt

title: Data licensing
start

:Find the data rights owner\n(copyright owner or representative);
note right: Non-trivial non-technical\nprocess
:Work with data rights owner to understand access and use rights;
note right: Non-trivial non-technical\nprocess

:Write an easy to read license;
' note right: Could TK Notices and Labels form\npart of a license?\n Maybe act as clauses?
note left: It's important to document\naccess and usage contraints\nin an implementation-neutral way\n           *IN ONE PLACE*
if (anyone can use) then (yes)
  :Use an open access license;

else (no; Authorization Step Required)
  if (Click-thru agreement\nwith terms or a short quiz\nis enough) then (yes)
    :Write a click-thru or\nquiz based license;
  else (no)
    if (Steward can list *exactly*\nwho should have access) then (yes)
      : Make an\nAccess Control List;

    else (no)
    
      :Design a form or other\nmechanism to approve\nagents\n(Some agents might\nbe pre-approved);
      :Identify decision maker(s)\nto grant licenses;


    endif
  endif

endif


@enduml
