
@startuml
!include_many ../data-management-style.txt

title: LDaCA data triage
start

if (Data is in an existing service) then (yes)
 
  if (Service can be sustainably Managed) then (yes)
    if (Need Preservation or working copy) then (yes)
      :Create exporter;
    else (no)
      :Set up Harvester or other integration;
       stop
    endif
  else (no)            
      :Migrate / transform data;
  endif
       
 
else (no)
endif

:Set up Arkisto Stack;
@enduml
