
@startuml
skinparam defaultFontSize 18

title: Super Simple License Server w/ Github Authentication & Authorization
actor       researcher     as res
entity    repository    as rep
entity    "License Server"    as gls
entity "https://doi.org/x/some-notebook" as c
database "groups" as gps
res -> rep : Can I have https://doi.org/x/some-notebook?
rep -> c : What's your licence?
c -> rep : Accessible to github org MyTroveData 
rep -> rep : Is that URL on the list of trusted sites?
rep -> rep : Yep
rep -> res : Authenticate yourself to license service
res -> gls : Logs user in using Github  
gls-> gps : User in MyTroveData org?
res -> gls : Yep
gls -> res : (To web browser) Here's a token for your browser that will let the repo get your group-memberships
res -> rep : (via browser) Here's a token
rep -> gls : I have this token
gls -> rep : yep
rep -> c : fetch
rep -> res : Here's the RO-Crate
@enduml

