
@startuml
skinparam defaultFontSize 18
title: Oni Architecture


rectangle "Oni API" {

database "Search and discovery Index" {

        rectangle "Object 1:\nDiaglogue" as A {
        
    }
        rectangle "Object 2:\nSub Collection Books 1" as B {
        
    }
        rectangle "Object 2:\nSub Collection Books 2" as C {
        
    }
        rectangle "Object 3:\nText"  as D{
        
    }
        rectangle "Object 3:\nVideos" as E {
        
    }
        rectangle "Object 3:\nAudios" as F {
        
    }

}


database "Data Location and license index" {
       rectangle "Object 1:\nData Location\nLicense" as o1 {

    }
    rectangle "Object 2:\nData Location\nLicense" as o2 {
        
    }
   rectangle "Object 3:\nData Location\nLicense" as o3 {
        
    }

}


database "File Repository" as repo {
    rectangle "Object 1:" as ro1 {
        rectangle "RO-Crate:\nMetadata\nData\nLicense" as ro11 {

        }
    }
    rectangle "Object 2:"  as ro2 {
                rectangle "RO-Crate:\nMetadata\nData\nLicense" as ro21 {

        }
    }
   rectangle "Object 3:" as ro3 {
                rectangle "RO-Crate:\nMetadata\nData\nLicense" as ro31 {

        }
    }
}

note top of ro31: Collection
note top of ro21: Two sub collection records
note top of ro11: Part of a larger collection

ro1 ---> A
ro2 ---> B
ro2 ---> C
ro3 ---> D
ro3 ---> E
ro3 ---> F

ro1 --up--> o1
ro2 --up--> o2
ro3 --up--> o3

}

cloud "Oni UI" {

}

"Oni UI" <-> "Oni API" : UI



@enduml

@startuml

database "Index" {
rectangle "Data & License index" as ii {

}
rectangle "Browse Index" as ai {

}
}

database ".......... OCFL Repo .............. \n\n\n\n\n\n\n\n\n\n\n\n" as repo {
    
}

rectangle "Indexer" {

}

rectangle "Config" as conf {

}

Indexer -up-> repo : Scan objects
Indexer -> conf : Consume
Indexer -up-> Index : Write

rectangle "API" {
    [item/] as iapi
    [query/] as qapi
    [license filter] as lic

}

cloud "Authentication and Authorizatio Services" as auth {
    [CILogon]
    [Mukurtu]
    [...]

}

rectangle "UI" {
  
}
lic -> auth : Get user's group/license holdings
UI --down--> qapi : Construct views
UI --down--> iapi : Get data for viewing
iapi --down-> ii : Consult for get requests\nfor Objects and files
qapi --down-> ai : Consult for queries / views\n*with license filter

API --down->  repo : Read

@enduml
