
@startuml
!include_many ../data-management-style.txt

title: Choosing a Data Repository


:Document Requirements;

note right
Size, Granularity, Access Control, APIs
end note




if (Is there standard repository for your discipline / field\neg PARADISEC, ADA, ALA...) then (yes)

   if (meets all requirements) then (yes)
      :Use Discipline Repo;
      stop
   else (no)
   endif
endif


if (You have Open Access Data)then (yes)


   if (Institutional repo exists & meets requirements) then (yes)
      :Use Institutional Repo;
      stop
   else (no)
        if (There's a suitable Generalist Repo) then (yes)
            :Use it;
         stop
         else (no)
   endif
   

endif

endif

note   
Assumption: Insitutional 
and generalist repositories
are Open Access only and
usually have size limits /
not suitable for collections-
type data
end note

if (You have project funding or eResearch Support) then (yes)

   :Start a project\n(potentially use RRKive tools);
   stop
         
else (no)
   : Follow RRKive advice about organizing data\non raw institutional storage\n(Use the the R: Drive) ;
   stop
endif







@enduml
