
@startuml
!include_many ../data-management-style.txt

title: Building Services on top of RRKive storage
start

:1: Build an index of\n  "Digital Objects";
note right
Create a lookup table of the archive:
- List IDs and their storage locations
- Build map of Collection / Object relationships

end note


if (Put online) then (yes)

:2: Set up ;
note right
- License
- Assign IDs (DOIs etc)
- Object<->Collection relationships 
- Who, what where
- File descriptions
- Provenance
end note



:🎉 Archival-Repository ready 🎉\n        status achieved ;
note right
Ready for institutional storage service
end note



:3: Index and catalogue the `RRKive`;
note right
Choose according to your means/requirements:
- Simple spreadsheet based summaries
- Portable database catalogues
- Access controlled API with license manager
- Full search features a la LDaCA/PARADISEC
- IDN-style "Data Catalogue"
- More coming ...
end note
@enduml
