@startuml
!include_many ../data-management-style.txt

title: Adding Objects using Crate-O (TODO)
rectangle "Repository with portal"  as arch <<repository>> {

   

        rectangle "API" as api1
   
    database "Storage 1" as stor1 {
        rectangle "Obj1" 
        rectangle "Obj2"
    }
    
}

rectangle "Editing Workspace"  as test <<workspace>> {
     database "Preview 'Repository'" as p1a {
     }
     
    

   
    rectangle "Crate-O Editor"  as CO {
          rectangle "Obj1a"
    }


}



api1 --right--> p1a : Checked out for editing / approval
Obj1a -right-> p1a : Draft
p1a -right-> CO: More editing
p1a  --down--> api1 : Check in new version\nor new object
api1 <-down-> stor1

@enduml