
@startuml

title: ATAP Ecosystem - Major Components

!include ../data-management-style.txt



rectangle "ATAP Website" as aw <<support>> {
rectangle "ATAP Data Portal" as adp {
rectangle "Tool Registry" as tr  {

}
rectangle "Data Collections" as dc {

}
}




rectangle "Data and Analytics Guides" as dag {


}

}

rectangle Workspaces as ws <<workspace>> {

database "Git Server\neg github, gitlab" as git {

}

rectangle "Binder Hub"  as bh {
}

rectangle "Nectar Virtual Compute"  as nectar {
}

}

bh -down-> git : Fetch notebook
bh -down-> nectar : Launch Notebook
rectangle "Archival Repositories" as ar <<repository>> {


database "ATAP repo" as a {


}
database "LDACA repo" as l {


}

database "Zenodo etc" as z {

}

rectangle "Institutional Data Repo" as z {

}

}


dc -down-> a : Index data
dc -down-> l : Index data
tr --down--> git : Index tools
dag -down-> ws : Link
@enduml
