@startuml
!include ../data-management-style.txt

actor Researcher as r
   skinparam defaultFontSize 30
   skinparam actorFontSize 30
   r -> "Browser" as b : I want to learn topic modeling. Do we have notebooks for topic modeling?
   "ATAP/LDaCA Repo" as port -> b : Here's three
   r -> b : What data do I need?
   b -> port : Does a notebook have an 'input' value?
 
   port -> r : Notebook 2 has input = CoOEE
   r -> "ATAP/LDaCA Repo" as port : Get me CoOEE
	port -> b : return CoOEE
	 r -> "ATAP/LDaCA Repo" as port : Get me Notebook 2
	 port -> b : Notebook 2 record w/"RUN ME" button
   b -> binderhub : Start Notebook 2
   binderhub -> b : Return live notebook
@enduml