
@startuml
!include_many ../data-management-style.txt

title: Batch-loading data into LDaCA, simplest view

rectangle "📈📄📜  Original Data 🎥🎙" as data {

}

rectangle "⚙️ 'Corpus Tool' conversion code ⚙️ " <<workspace>> as ct {

}

note top of ct : Tool is corpus specific

database "OCFL Repository" <<repository>>  as repo {

}

ct <-up- data : Convert to RO-Crate\n(using Language Commons profile)
ct -down-> repo : Write data 

@enduml
