
@startuml

title: LDaCA Data preparation
!include_many ../data-management-style.txt



rectangle "📈📄📜  Folders of legacy or novel data 🎥🎙" as data {

}

rectangle  "Data Preparation Workbench: Make Research Objects" <<dataprep>> as dp {
rectangle "Corpus Tools" as ct {
    rectangle "Custom scripts" as ctscripts
    rectangle "RO-Crate Excel" as ctexcel

}
  rectangle "Data Annotation Tool: (Crate-O)"  as co {
   rectangle "Interactive Web Forms" as forms
   rectangle "Excel Import" as excel
  }


rectangle "Plugins" as pi {
  
}

dp --down--> co
pi --down--> co
ct --down--> co
}


note top of pi
 - Extend Workbench functionality
 - Custom plugins for specific data types or tasks
 - Examples:
    - OCR for images
    - Auto transcription for audio
    - Text to TEI conversion
    - Word transcriptions to CSV or other formats
 - Run in:
    - Local machine
    - Binderhub
    - Commercial API services
end note



database "Repository" as repo <<repository>> {
    rectangle "RO-Crate 1" as 1
    rectangle "RO-Crate 2" as 2
    rectangle "RO-Crate 3" as 3
    rectangle "RO-Crate n" as n
    1 -[hidden]> 2
    2 -[hidden]> 3
    3 -[hidden]> n
}

rectangle "⚙️ API ⚙️ "  as api {

}

dp <--up-- data : Upload or share data via sync service
dp --down--> repo : Write crate(s)
repo -down-> api : Serve data

rectangle "Data Transformation Tools" <<workspace>> as dtt {
    rectangle "RO-Crate to Table (Tabulator)" as tablr {
        rectangle "CSV Export" as csv
        rectangle "Pandas DataFrame Export" as pandas
        rectangle "Parquet Export" as parquet
        rectangle "SQL Export" as sql
       

    }
    rectangle "Corpus Loader (SIH)" {

    }
     rectangle "Corpus Export" as corpus {
            rectangle "AntConc" as ac
        }
}

dtt -down-> api : Fetch research objects
dtt --up--> dp : Use Research Objects directly 

cloud "Analytics Environment\n(Jupyter Notebooks, RStudio, etc)" <<workspace>> as analytics {
    rectangle "Data Analysis & Visualization\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" as dav
}

analytics --up--> dtt : Use transformed data
@enduml
