@startuml
skinparam defaultFontSize 18

!define ENTITY #lightblue

ENTITY "Rights Owner"
ENTITY Custodian
ENTITY Steward

"Rights Owner" -down--> Custodian : Storage\nand access
Custodian -left--> Steward :  Storage and access
Steward -up--> "Rights Owner" : \n\nProcessing
Steward -right--> Custodian : -

@enduml