@startuml
!include_many ../data-management-style.txt

package "RO-Crate 1"  {
    rectangle "Machine Readable Metadata\nro-crate-metadata.json" as json {
         rectangle "What type of data 🅾️" as type {

        }
        rectangle "🧑 Who was involved 🧑🏽‍🔬" as who {

        }
        rectangle "❓ What is this about ❓" as  what {

        } 
        rectangle "🗺️ Where was it collected 🗺️" as  where {

        }
        rectangle "📁 What is in each file 📁" as files {

        }
        rectangle "♻️ How can data be resued and by whom ♻️" as lic {

        }

    }


    rectangle "Web page: Human Readable Metadata  \nro-crate-preview.html\n\n\n Type: Object\n Modalty: Spoken\n DateCreated: 2022-01-30\n etc." as html

    package "Files"  as data {
     rectangle "LICENSE.txt" as lict
     rectangle "data/\n   transcriptions/\n   audio/\n   video/" 
     }
}
files -down-> data : Describe
    type -down[hidden]-> who
    who -down[hidden]-> what
    what -down[hidden]-> where
    where -down[hidden]-> files
    files -down[hidden]-> lic
    lic -> lict 
   html -up-> json : Derived from

@enduml