@startuml
!include_many ../data-management-style.txt

rectangle "Authorization and Authentication" as auths <<authorization>> {
    rectangle "License Management" as lic
    rectangle "Attribute & Certification\nManagement" as att
    rectangle "Identity Authentication" as id

}

id -down-> lic
att -down-> lic

@enduml

