
@startuml
title: Abstract FAIR architecture for standards based archival repositories
!include_many ../data-management-style.txt
!include_many ./authorization-components.puml
!include_many ./archive-components.puml
!include_many ./standards-components.puml

rectangle "FAIR + CARE \n\n"  as FAIR {
rectangle "  F  " as F
rectangle "  A   " as A
rectangle "  I  " as I 
rectangle "  R"   as R
}
F -right[hidden]-> A
A -right[hidden]-> I
I -right-> R



ro -down-> Profiles
Profiles  -down[hidden]-> PIDs

database "FDO1" {

}

note left of FDO1: "FDO === FAIR Digital Object"

database "FDO2" {

}

I -up-> FDO1 
FDO1 -right-> ldac : Conforms to
FDO2 --down--> 1 : Deposit
FDO2 <--down-- 1 : Fetch
FDO2 <-up- R
disco <-> api
api -- A : Authorize\nall\nrequests

FAIR -down[hidden]-> arch
F <--down--> disco
A --up--> lic
@enduml
