@startuml


rectangle "Standards" <<standards>> {
    
    package "RO-Crate" as ro {
        rectangle "Schema.org"
        rectangle "JSON-LD"
    }
    rectangle "PIDs" {
      rectangle "DOI"
      rectangle "ARCP"
      rectangle "Managed URIs"
    }
    rectangle "Profiles" {
        rectangle "Language Data" as ldac
        rectangle "Workflow Run" as wr
        ldac -down[hidden]-> wr
    }
}
@enduml